theme: minima
title: "Ankit Maloo"
author:
  name: "Ankit Maloo"
  email: "ankit@clioapp.ai"
description: >
  Documenting my journey in the world of AI and RL.

# Add the line below:
permalink: /:title/
